openapi: 3.0.0
info:
  title: server
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
paths:
  /numbers:
    get:
      summary: 数字一覧を返す
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  numbers:
                    type: array
                    items:
                      type: integer
        '400':
          description: Bad Request
      operationId: get-numbers
      description: ''
      parameters:
        - schema:
            type: integer
          in: query
          name: from
        - schema:
            type: integer
          in: query
          name: to
